### ISSUE TITLE
fireloop doesn't work with mysql database

### ISSUE THREAD

**Issue by mhmo91** [mean-expert-official/fireloop.io#100]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other

Write other if any:
1.0.0-beta.2.5
#### Please add a description for your issue:
i created a project with angular web app, everything works fine if the model is connected to in memory db, but when i change to mysql, the realtime queries doesn't work, observers don't resolve, and the rest-apis are working perfectly fine.

**Comment by mhmo91** [comment]
i have created a repo for the test project i created here 
https://github.com/mhmo91/fireloop-sample-app
Also, i'm using xampp to run mysql server

**Comment by hasahmad** [comment]
Mine is working and I don't have `"url": "",` in `server/datasources.json`

`
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mysqldb": {
    "host": "localhost",
    "port": "3306",
    "database": "api",
    "password": "password",
    "name": "mysqldb",
    "connector": "mysql",
    "user": "root"
  }
}
`

**Comment by jonathan-casarrubias** [comment]
@mhmo91 FireLoop will work regardless the datasource,

The only moment when a non-sql datasource is important is when you want to scale to multiple servers, http://docs.fireloop.io/en/scaling-fireloop/.

I think you might have an issue because a recent update to the @mean-expert/loopback-component-realtime module now requires the "FireLoop" mixing to be registered on each model you want to enable the real time...

Take a look on this issue: https://github.com/mean-expert-official/loopback-component-realtime/issues/38
