### ISSUE TITLE
failed: Error in connection establishment: net::ERR_ADDRESS_INVALID

### ISSUE THREAD

**Issue by zmazouzi** [mean-expert-official/fireloop.io#109]
the tutorial about creating Real time statsExample with fireloop  doesn't work 
link of tutorial by MEAN.EXPERT :  http://docs.fireloop.io/en/realtime-stats-example/

here is the error : 

2VM235:35 WebSocket connection to 'ws://0.0.0.0:3000/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID
WrappedWebSocket @ VM235:35
65VM235:35 WebSocket connection to 'ws://0.0.0.0:3000/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_ADDRESS_INVALID

**Comment by jonathan-casarrubias** [comment]
@zmazouzi thanks for reaching out,

hey so.. just make sure you are actually running both, the server and the client.

Because of the error I'm assuming the server is not running

**Comment by zmazouzi** [comment]
thank you for that awesome tool ..yes both the server and the client are running  but it doesn't seem to work , we are using windows 10 can it be the problem ,  thank you for your help 

we are using the : FireLoop Version: 1.0.0-beta.2.6

![44](https://user-images.githubusercontent.com/19895489/27710289-c014b328-5d0e-11e7-91b0-107557029d97.PNG)

**Comment by enimiste** [comment]
Hi,

I have the issue i run the command `fireloop serve`  and i have the two servers running ( i can get to http://localhost:3000/explorer and http://localhost:4200) but when i open the console of chrome on the angular part i get the same message.

I use also Windows 10. Is this specific to the OS ?

Thanks

**Comment by enimiste** [comment]
I had a discussion on Fireloop Slack with @davexs2020 and @jonathan-casarrubias and this is a Windows users issue :
### First :
To have two options :
- User the last release of fireloop (published yesterday)
- Or, Add mixins from this repo : [https://github.com/mean-expert-official/loopback-component-realtime](https://github.com/mean-expert-official/loopback-component-realtime)

### Next :
- And you should edit `server/config.json` file and use `127.0.0.1` instead of `0.0.0.0`, then regenerate your client SDK (Worked for me)
- Or jsut set the loopback config in your client like : `LoopBackConfig.setBaseURL('http://127.0.0.1:3000');` and don't forgot to import `import { LoopBackConfig } from './shared/sdk/lb.config';` (I didn't test it yet)


### Tips :
When creating a new fireloop project you should choose :
- `v3 (current)` for loopback
- Only this option : `Enable PubSub + IO + FireLoop functionality`

Thanks a lot

**Comment by jonathan-casarrubias** [comment]
Hi guys

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
