### ISSUE TITLE
Graceful shutdown blocked by loopback-component-realtime

### ISSUE THREAD

**Issue by ChristianLimes** [mean-expert-official/fireloop.io#134]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [x] Other
1.0.0-beta.2.7

Write other if any:

#### Please add a description for your issue:

Hy,
I try to implement a graceful shutdown (npm install express-graceful-exit) into fireloop. Unfortunately, it does not work. I start with a clean install of fireloop as an „api-server“, but it also doesn't work.

The server doesn’t shut down because of the real-time engine (@mean-expert/loopback-component-realtime). When I drop „@mean-expert/loopback-component-realtime“ from „component-config.json“ the shutdown works perfectly. 

Is there a way to shut down „loopback-component-realtime“ from server.js?

Thank you for your help.

**Comment by jonathan-casarrubias** [comment]
Hi @ChristianLimes, well your description would be an unexpected behaviour, we would need to verify how to fix this issue.

I believe this is a design problem since LoopBack 1~3 does not provide a way to shut down loaded components, we might workaround by using an internal app.event, but I'm not entirely sure at what point you would send that event.

For instance in LoopBack 4 I'm already building the gRPC module for the next version of FireLoop and it does provide a way to shut down the extension, so I guess I don't have the right answer for your question now

**Comment by ChristianLimes** [comment]
Hi, @jonathan-casarrubias sounds great if you add this module to the next version. 
I want to shut down the server by docker container.
The docker container gets a signal from us to shut down. Then the container sends a "SIGTERM" signal to fireloop that we catch. If we get this signal we can close all open connections (Database)

**Comment by jonathan-casarrubias** [comment]
Hi @ChristianLimes 
Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
