### ISSUE TITLE
Fireloop will support three way databinding like firebase?

### ISSUE THREAD

**Issue by ittechsathish** [mean-expert-official/fireloop.io#136]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [* ] Question

**Comment by jonathan-casarrubias** [comment]
Hi @ittechsathish I think adding 3w data binding would be awesome in the next version of FireLoop.

I don't think it will be possible for the current version, since everything now is being refactored due LoopBack 4 (Next), so all of these new features won't run under the current version

I hope this clarifies your question

**Comment by jonathan-casarrubias** [comment]
Hi @ittechsathish 

Hey so, I really want to apologize for saying this but I'm stopping the support for FireLoop or any LoopBack module I built.

I'm working on a new project from scratch that of course is not built on top of LoopBack or anything else, this new project will also provide a SDK but now it won't be FrameWork specific, therefore you should be able to use it in Angular 5, React, Vue or even plain JavaScript projects


I apologize if you started a project on FireLoop, here I give a more detailed explanation:
https://github.com/mean-expert-official/fireloop.io/issues/137
