### ISSUE TITLE
Support for fireloop

### ISSUE THREAD

**Issue by JeetChaudhari** [mean-expert-official/fireloop.io#145]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

Hi Jonathan, If you remember we have communicated before on slack channel you created for fireloop. 

Few days before you declared that you will not be working on fireloop anymore as you are going with OnixJs, which is awesome by the way. I really liked the concept and looking forward to using it in new projects that my company would build for clients. However, in past my company Aceonics built few projects using fireloop as it was a great choice to have real-time features with generated API of loopback. 

Now the problem is there is no support for the fireloop package used in projects of my clients. Also, we have some large projects which are being worked on using fireloop which require documentation to be working, few important issues to be solved, features and changes to be added in fireloop. So now I have few options as follows.

1. Get fireloop working again with docs running and implement the changes that we need to go forward with our client's in progress projects as well as provide support for their applications.

2. Update existing client's projects to use OnixJs but it seems a lot of work as projects are very dependent on loopback's features and using OnixJs means we have to create API again which increases cost. We can go with rest gateway feature of OnixJs but it is paid option as per pricing and I don't think that my clients would be happy to pay that much amount, it is just out of their budget.

3. Modify projects to not use fireloop but implement a very simple feature to provide real-time functionality using socket.io.

Looking at these facts I found option 1 to be most easy and efficient for us and decided to go with it. If you have any better solution please let me know. However to continue with the 1st option I have few questions in mind as follows. If possible please reply my questions. Also if you find these questions very basic or stupid, please forgive me, I never handled any open source project before, only used those but now thinking of keeping the support of fireloop alive for people like me who have projects running with fireloop.

1. Is it (legally) okay for me to add these fireloop codes (all fireloop related repositories) under my name to npm lib, means aceonics/fireloop.io, of course as the main author your name and details will be on every file as it is now with our added line as modified by Aceonics? So that we can make our required changes in those forked projects and continue using it as @aceonics/loopback-component-realtime instead of @mean-expert/loopback-component-realtime?

2. Can I change the name of the package? Means right now this fireloop package is named as fireloop.io, however, this domain now points to OnixJs so can I get rid of this name? If yes then is there any requirement that I need to follow to get this done?

3. My staff wanted running docs of fireloop so I have currently hosted fireloop docs at https://fireloop-docs.netlify.com , do you want me to take it down or can I keep it running?

Let me know your opinion on this. Thank You

**Comment by jonathan-casarrubias** [comment]
Hi @JeetChaudhari thanks for reaching out,

Hey so... yeah I did shut down any fireloop server because of the cost of having those... Actually either the mean.expert domain or the fireloop domains where shut down because of the same reason..

After a month or so of being down.... then I got a free year of a google cloud instance where I'm running today OnixJS related services and websites, I didn't publish anything related to fireloop or mean.expert more likely because I'm dedicating about 14 hours the day to OnixJS.

So, that is the real reason I decided to point those domains to OnixJS.

Anyway.... I will answer your 3 questions from your option 1.

1.- Yes is legal for you to add those codes and repositories under your name on NPM. The MIT license allows you that and you would only be required to keep the name of the original author as you said before.

2.- Yes is legal to actually change the name, since the MIT license is the more permissive license on the open-source community.

3.- Yes is legal for you to actually host the documentation and anything related to these packages as long as you keep the name of the original author, similar to what I did to the Bajtos' code. Just keep the name and everything else is ok.

Anything you can do to help your former team and customers will be legal and accepted by me in the terms that I did the research on licenses and I'm aware that I decided to go with the more flexible one, because at the end... FireLoop never was a capital venture, but an open-source venture to help the community around loopback to grow.

If am being clear, you are actually free to do basically whatever you are proposing and I will be fine because of the original spirit of this project.

Talking about OnixJS, yes the REST Gateway will be a paid module, though I still don't document it but you can also build REST Apis for free using the API Artifacts, though I don't believe migrating to OnixJS your large clients or former clients at this point a good idea, mainly because:

1.- More than a half of the current published features are not documentd.
2.- I would never recommend to use an alpha version into production projects.
3.- I want to make sure that all the provided OpenSource features are enough for developers to entirely build a project, I still need to provide a couple of those.


I hope you guys to understand that I did invest a lot of time and effort around the MEAN stack community, that literally gave me 0 dollars while those guys from loopback -that I personally know- spend their IBM dollars in really expensive toys.

But I will never leave my love to the community so with OnixJS I will provide you with the right tools to do great things for free, but I do need to provide modules that also bring some food to my table.

I hope you guys to understand that.

Best Regards,
Jon

**Comment by JeetChaudhari** [comment]
Hi, @jonathan-casarrubias thanks for replying my questions.

I am glad to know all positive answers from your side to my proposal. I will soon set up all the required things to get this going. 

I will do the needful for the community using fireloop in their existing projects. 

Best Regards,
Jeet
