### ISSUE TITLE
[Windows 10] CLI just closing

### ISSUE THREAD

**Issue by John0x** [mean-expert-official/fireloop.io#17]
Hey, I've tried running the cli. The problem is that it just closes my cmd. No output or whatsoever.

I guess it just not intended to work, right?

**Comment by jonathan-casarrubias** [comment]
Hey @John0x thanks for reaching me out!

I'm glad people is starting to use this platform. So, just to understand the context... You just installed `npm install -g @mean-expert/fireloop`, and when you run the command `$ fireloop` it just closes? no command, nothing displayed?.

If that is the case, would you mind if you describe your environment?

OS?
Node Version?
NPM Version?

I will try to verify in different machines today and see if I can replicate, but it should not close your terminal. It should display a Yeoman interface that should help you create the project.

Cheers!
Jon

**Comment by John0x** [comment]
Hey,

yeah, thats exactly what I did.
OS: windows 10 insider build 64bit
Node: 3.10.8
node: 7.0.0

It closes the entire window not just runs through without output.

**Comment by jonathan-casarrubias** [comment]
I see...

I just verified in another Mac and does work, I'm testing with same npm and node version you have... It seems is something related to Windows.

I'll need to get one windows machine to test, it may be something simple but ok looks like I know how to replicate this then.

**Comment by John0x** [comment]
When I start the fireloop.cnddireclty (in %AppData%\npm\fireloop.cmd) it works without problems.

**Comment by jonathan-casarrubias** [comment]
Hey @John0x thanks for looking at it, so the `generator-fireloop` should be automatically installed as a dependency when you install the cli.

Inside the CLI Tool I use require.resolve to get the module filesystem directory and then execute the generator which is the one that actually bundle everything together.

So it looks like its trying to get this generator file `generator-fireloop/generators/$@` but not sure why it display $@ or where does it come from, it looks like it was changed instead of an actual command like `generator-fireloop/generators/model` where model is variable depending on what command you pass after the fireloop one

`$ fireloop model` should be translated to `generator-fireloop/generators/model`
`$ fireloop serve` should be translated to `generator-fireloop/generators/serve`

If you have access to the fireloop module, and just console log the argv variable, maybe in windows is differently organized.

# Another thought:

Inside the fireloop binary I have a validation when no command/argument is passed, it should run the general menu interface. Maybe and just maybe in Windows when you run `$ fireloop` there is always an unexpected  argument and therefore does not enter the right validation and then executes a weird $@ command, leading to this issue

I believe this is the failing validation due the $@ command when running `$ fireloop` https://github.com/mean-expert-official/fireloop.io/blob/master/bin/fireloop.js#L28

Maybe it should be something like:

``` js
if (!argv._ || argv._.length === 0 || argv._[0] === '$@') {
...
}
```

**Comment by John0x** [comment]
Hey, I first tried to install it using yarn, but then removed it again from yarn.
Seems like it wasn't cleaned up or something. 

It works now, after deleting everything manually.
Thanks for your help and keep up the great work! :)

**Comment by jonathan-casarrubias** [comment]
Awesome!!! I'm glad it loads now!!! That was scary lol...

So it still is on alpha version, but good progress is on it. The goals is to provide a single tool that bundles all (Including Universal -Soon Soon-).

I hope you have fun this with new technology.

Cheers!!!
Jon
