### ISSUE TITLE
Install failed due to Fiber

### ISSUE THREAD

**Issue by John0x** [mean-expert-official/fireloop.io#19]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question
#### What version of this module are you using?

Newest from NPM
Node: v7.0.0
Npm: v3.10.8
OS: Windows 10 insider
#### Please add a description for your issue:

Hey, I tried to install/update fireloop this morning and it doesn't install the packages properly anymore.
Command: npm install -g @mean-expert/fireloop
The reason seems to be the fiber package.

Error message:
First:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\software\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14931
gyp ERR! command "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\johnb\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\node_modules\fibers
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-gyp exited with code: 1
```

Second:

```
npm ERR! Windows_NT 10.0.14931
npm ERR! argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@mean-expert/fireloop"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
```

**Comment by jonathan-casarrubias** [comment]
Hi @John0x, yesterday I gave a training and we were having similar issues also with some dependencies not being installed by NPM.

Actually we just installed again and the issue disappeared, but I believe this is all after I integrated nativescript, it seems there are too many dependencies to be installed that some fail.

I believe I will rollback the nativescript part and see it returns to stability

**Comment by John0x** [comment]
Hey @jonathan-casarrubias, I tried to remove everything and install it again (and twice without removing), though came to the same result.

**Comment by jonathan-casarrubias** [comment]
@John0x , I'm about to publish a rollback without nativescript and see if does install now.

It will be in around 10m

**Comment by jonathan-casarrubias** [comment]
@John0x is published now.

Im trying:

``` sh
$ npm uninstall -g @mean-expert/fireloop
$ npm cache clean
$ npm install -g @mean-expert/fireloop
```

I'll verify if does install now

**Comment by jonathan-casarrubias** [comment]
Ok great, it seems to be working again... Could you confirm

**Comment by John0x** [comment]
Confirming. Installs again, without problems. Thanks :)

**Comment by jonathan-casarrubias** [comment]
Awesome!!! I believe I will need to delegate the installation of the client modules instead of trying to install all,.

What do you think of this:

FireLoop will detect if the user has installed a core client dependency, e.g. `nativescript | angular-cli | ionic`, in which case I would enable the respective section within fireloop, instead of trying to install all through the FireLoop installation.

Other option is to have enabled the options but requesting to install the core dependency when selecting the option, I don't like this one so much because once you see the option you want to use it right away, installing after that can be annoying, you think?

What is the better user experience from your perspective?

I appreciate your interest on this.

Cheers
Jon

**Comment by John0x** [comment]
Hey @jonathan-casarrubias, great, thanks for your help :)
Well, in my case for example, I have all three dependencies installed (globally), but I would only want to use one of the three iny my fireloop project. 
I think the best option would be just to ask the user upon initializing (first time running fireloop), which dependencies he want's to use.

Alternateviley you could just mention in the readme that one or more of those dependencies are needed to be installed globally like ionic does for example. They just tell you in their readme that you need to have cordova installed.
And in case that they try to use something which they don't have the dependencies installed for you could just warn them and tell them to install it.
That way the user could decide on his own what dependencies he want's to install.

**Comment by jonathan-casarrubias** [comment]
Hi @John0x, thanks for your comments I will address these and delegate the core dependencies to users.

Also I got this other issue: https://github.com/mean-expert-official/fireloop.io/issues/21 where it seems that nothing works in windows.

Since you just created an issue for the installation I'm wondering if you was totally unable to do anything like in the #21.

I'm having a hard time here because I'm surrounded of macs to the points is getting annoying lol.

Any help on this would be appreciated.

Cheers
Jon

**Comment by John0x** [comment]
Hey @jonathan-casarrubias generating the projects worked for me without problems. I'll test it again with the newest version and leave a comment on the #21 issue.
