### ISSUE TITLE
Error when calling Model generator

### ISSUE THREAD

**Issue by roboflank** [mean-expert-official/fireloop.io#75]
#### What type of issue are you creating?
- [x] Bug
- [ ] Enhancement
- [ ] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

I update my CLI to `1.0.0-beta.2.4` and now i cant be able to do a `fireloop model Modelname` 

Anything changed?

**Comment by roboflank** [comment]
`events.js:163`
  `   throw er; // Unhandled 'error' event`
      `^`
`Error: No API server was found`

Am getting this error.

**Comment by roboflank** [comment]
Fixed this, by adding server dir to the config

**Comment by roboflank** [comment]
Running into another error

`events.js:163`
      `throw er; // Unhandled 'error' event`
      `^`

`Error: You don’t seem to have a generator with the name “loopback:model” installed.`

**Comment by jonathan-casarrubias** [comment]
@denzelwamburu yes something changed actually.

Since you can now set the name of the API directory, previously was fireloop by default, now there is an extra configuration within the .yo-rc file

In order for your project to work with the new cli, you will just need to update the yo-rc file as follows

````json
  "generator-fireloop": {
    "version": "1.0.0-beta.2.3",
    "clients": {
      ----- HERE YOUR CURRENT APP ------
      "fireloop": {
        "path": "./fireloop",
        "type": "server"
      }
    }
  }
}
````


Or you can also create a new project and migrate your code, just keep the new setup.

Cheers
Jon

**Comment by roboflank** [comment]
Thanks, I figured that out.
Though my model generator still throwing an error.

**Comment by jonathan-casarrubias** [comment]
I just verified and I'm able to create models without any problem.

Try with a clean installation and see if the problem persist
