### ISSUE TITLE
Will server.js be converted to typescript?

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/fireloop.io#80]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

I was wondering because all of the files are in .ts except for server.js
Is this a limitation of loopback or something you have planned to do in the future?

**Comment by jonathan-casarrubias** [comment]
@dmastag it is on JS because the project should be able to run as any other node js project, internally we transpile in runtime the TS files  by using ts-node, so you don't need to later compile.

It is possible that by LB4 that will be all typescript that might change, depending on their final implementation..

Regards!
