### ISSUE TITLE
Migration path for existing Loopback projects

### ISSUE THREAD

**Issue by proreact-mj** [mean-expert-official/fireloop.io#85]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [X] Question

#### What version of this module are you using?
- [X] 2.1.0-beta.n (2.1 Beta n)
- [ ] Other

Write other if any:

#### Please add a description for your issue:

We are already running a fairly complex Loopback app, but are considering upgrading our frontend focus from AngularJS to Angular 2/4. Fireloop seems like a perfect abstraction to really get some nice functionality. 

However, I can't see to find any information about a migration path for an existing Loopback (2) project to Fireloop. Am I missing some important resource or is it a potential enhancement in the area of examples/documentation. 

Another thing is that the CLI seems to do a lot of magic, but we usually like to just do Loopback directly in the source (both JSON and JS) and run the server app in PM2. Are the any caveats to this approach in a Fireloop context (manually adding mixins, maintainance in other areas, runner configurations or other automagical stuff?

**Comment by jonathan-casarrubias** [comment]
@proreact-mj it depends on how much functionality you want to get or not from the FireLoop platform.

For instance if you are only interested in implementing the real-time API from fireloop into your current LoopBack project, then you just need to install and configure the loopback-component-realtime and the loopback-sdk-builder.

With these 2 modules you can have a SDK for Angular 2+ App and LoopBack enabled for real-time communication.

Basically follow the README in here https://github.com/mean-expert-official/loopback-component-realtime and you will be able to setup that...

That project would not run on the FireLoop CLI since there are other modifications like having the models in TypeScript that would require you to create a new project using the CLI... There is no documentation or easy way to transform your current project into a FireLoop one.

I hope this information helps you clarify your questions.

Regards
Jon

**Comment by proreact-mj** [comment]
I was afraid of that. 
Too bad Strongloop didn't jump on the typescript wagon when they had the chance with v3 :(

I'll focus my efforts on the SDK generator and the realtime components as seperate (closely related) things for the existing project. 

Thanks for the quick answer and for all the love and sugar you are adding to Loopback (the Angular2 SDK builder is fantastic!).
