### ISSUE TITLE
Ionic2 and Fireloop

### ISSUE THREAD

**Issue by swfredrik** [mean-expert-official/fireloop.io#87]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [x] Question

#### What version of this module are you using?
- [x] 2.1.0-beta.4 (2.1 Beta n) latest
- [ ] Other

Write other if any:

#### Please add a description for your issue:

Im using Fireloop in my ionic2 application and its working great. My app contains of a listview where the user can click on an Item to see the details. When you click back and forth to the details view the app starts getting slower and slower to get responses. Is there anyting I should think of when "unsubscribing" and subscribing to fireloop models? 

Also, If I idle for a long time the connection gets disconnected, or at least im not getting any updates, is there any reconnect method I can use when the app becomes in view?

**Comment by dmastag** [comment]
Could you share some code?
Its hard to know what is wrong without knowing what you did.

**Comment by jonathan-casarrubias** [comment]
@swfredrik I'm not sure about the disconnection, since it is a persisted connection it will be only released by the network if there is no data being sent for a while, but that is being already internally handled by a heartbeater that sends a timestamp message every second or so to the server in a ping pong approach.

Other type of disconnections are handled by socket.io and once there is a network available it will try to reconnect.

Related to the performance, FireLoop uses Hot Observables that keeps living to receive more information in the future, therefore you need to be really careful because when you move out from a component, you should dispose your references and unsubscribe your subsriptions.

See this component as example: https://github.com/mean-expert-official/fire-starter/blob/development/webapp/src/app/home/todo/todo.component.ts#L38

I hope this helps you clarify your questions

Regards
Jon

**Comment by swfredrik** [comment]
The todoservice is incomplete? 
Can you show an example of how to create an Angular data service? how to consume that service in multiple views. I cant figure out how to pass the todos observable to multiple components. 

IF think it would be good to have a service that hook up to the realtime stuff, instead of having the same realtime code in multiple components.

**Comment by jonathan-casarrubias** [comment]
@swfredrik If I'm understanding well, I think you are losing the focus, the original issue ask 2 questions:

1.- Why is getting disconnected (I can not be sure of this)
2.- The performance decreases on each section navigation.

For the number 2 you need to unsubsribe and dispose your references as per the link which points to the following code:

````js
  ngOnDestroy() {
    this.todoRef.dispose(); // Dispose your model references
    this.subscriptions.forEach((subscription: Subscription) => subscription.unsubscribe()); // unsubscribe from all the subscriptions
  }
````

That is all you need to do to avoid performance issues on navigation, so in this case the answer is not related to the todoService.


I hope this helps you clarify your original question
