### ISSUE TITLE
type definition for loopback app instead of using var

### ISSUE THREAD

**Issue by mhmo91** [mean-expert-official/fireloop.io#99]
#### What type of issue are you creating?
- [ ] Bug
- [ ] Enhancement
- [#] Question

#### What version of this module are you using?
- [ ] 2.1.0-beta.n (2.1 Beta n)
- [#] Other 

Write other if any:
1.0.0-beta.2.5
#### Please add a description for your issue:
why there is no type-definition for the loopback server app?  
![image](https://user-images.githubusercontent.com/3815200/26883910-c019da46-4b9e-11e7-8f5d-426f69b7c618.png)

**Comment by jonathan-casarrubias** [comment]
@mhmo91 we were addressing the typing for the App, but now that IBM is working in a Typed Version of LoopBack, we will leverage that when the moment arrives.

Unfortunately LoopBack is having an entire rewrite, so we will take an strategy to update FireLoop with the new LB4 version, though I don't think we will continue using the model decorator or things like that in the future since LB will offer that, we will continue providing the RealTime capabilities.

I hope this answers your question..

Regards
Jon!
